# Generated by Django 5.0 on 2024-01-01 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_chat_participants_chat_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chaw'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
